import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import http from 'http';
import path from 'path';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import mongoose, { Schema } from 'mongoose';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import { v2 as cloudinary } from 'cloudinary';
import { Server } from 'socket.io';
import { z } from 'zod';
import { createServer as createViteServer } from 'vite';
import { MongoMemoryServer } from 'mongodb-memory-server';

const app = express(), server = http.createServer(app), PORT = Number(process.env.PORT || 3000);
const secret = process.env.JWT_SECRET || 'dev-fuelflow-secret-change-me';
const io = new Server(server, { cors: { origin: process.env.CLIENT_URL?.split(',') || true, credentials: true } });
if (process.env.CLOUDINARY_CLOUD_NAME) cloudinary.config({ cloud_name: process.env.CLOUDINARY_CLOUD_NAME, api_key: process.env.CLOUDINARY_API_KEY, api_secret: process.env.CLOUDINARY_API_SECRET });
app.use(helmet({ contentSecurityPolicy: process.env.NODE_ENV === 'production' ? undefined : false }), cors({ origin: process.env.CLIENT_URL?.split(',') || true, credentials: true }), express.json({ limit: '1mb' }), rateLimit({ windowMs: 900000, max: 300 }));

const opt = { timestamps: true, versionKey: false as const };
const User = mongoose.model('User', new Schema({ name: { type: String, required: true }, email: { type: String, unique: true, required: true, lowercase: true }, password: { type: String, required: true, select: false }, phone: String, role: { type: String, enum: ['OWNER','WORKER','ADMIN'], default: 'OWNER' }, profileImage: String, assignedStations: [{ type: Schema.Types.ObjectId, ref: 'Station' }], isActive: { type: Boolean, default: true } }, opt));
const Station = mongoose.model('Station', new Schema({ stationName: { type: String, required: true }, owner: { type: Schema.Types.ObjectId, ref: 'User', required: true }, address: { type: String, required: true }, city: { type: String, required: true }, state: { type: String, required: true }, pincode: { type: String, required: true }, contactNumber: { type: String, required: true }, fuelTypes: { type: [String], default: ['Petrol','Diesel'] }, petrolPrice: { type: Number, required: true, min: 0 }, dieselPrice: { type: Number, required: true, min: 0 }, operatingStatus: { type: String, enum: ['ACTIVE','INACTIVE'], default: 'ACTIVE' }, workers: [{ type: Schema.Types.ObjectId, ref: 'User' }] }, opt));
const Report = mongoose.model('Report', new Schema({ station: { type: Schema.Types.ObjectId, ref: 'Station', required: true }, worker: { type: Schema.Types.ObjectId, ref: 'User', required: true }, reportDate: { type: Date, required: true }, petrol: { opening: Number, closing: Number, litres: Number, price: Number, revenue: Number }, diesel: { opening: Number, closing: Number, litres: Number, price: Number, revenue: Number }, grossRevenue: Number, expensesTotal: { type: Number, default: 0 }, netRevenue: Number, status: { type: String, enum: ['DRAFT','SUBMITTED','REVIEWED','APPROVED','REJECTED'], default: 'SUBMITTED' }, rejectionReason: String, notes: String, bills: [{ url: String, publicId: String, name: String }] }, opt));
const Payment = mongoose.model('Payment', new Schema({ station: { type: Schema.Types.ObjectId, ref: 'Station', required: true }, report: { type: Schema.Types.ObjectId, ref: 'Report' }, worker: { type: Schema.Types.ObjectId, ref: 'User', required: true }, amount: { type: Number, required: true, min: .01 }, paymentMethod: { type: String, enum: ['CASH','UPI','CARD','CREDIT','OTHER'], required: true }, transactionReference: String, description: String, transactionDate: { type: Date, required: true } }, opt));
const Expense = mongoose.model('Expense', new Schema({ station: { type: Schema.Types.ObjectId, ref: 'Station', required: true }, report: { type: Schema.Types.ObjectId, ref: 'Report' }, category: { type: String, enum: ['Electricity','Maintenance','Staff','Transportation','Supplies','Equipment','Other'], required: true }, amount: { type: Number, required: true, min: .01 }, description: String, expenseDate: { type: Date, required: true }, receipt: { url: String, publicId: String, name: String }, uploadedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true }, status: { type: String, enum: ['PENDING','APPROVED','REJECTED'], default: 'PENDING' } }, opt));
const Notification = mongoose.model('Notification', new Schema({ recipient: { type: Schema.Types.ObjectId, ref: 'User', required: true }, title: String, message: String, type: String, isRead: { type: Boolean, default: false } }, opt));
type AR = Request & { user?: any };
const userJson = (u: any) => ({ id: String(u._id), name: u.name, email: u.email, phone: u.phone, role: u.role.toLowerCase(), profileImage: u.profileImage, active: u.isActive, assignedStationIds: (u.assignedStations || []).map(String), createdAt: u.createdAt });
const auth = (req: AR, res: Response, next: NextFunction) => { try { const t = req.headers.authorization?.split(' ')[1]; if (!t) throw 0; req.user = jwt.verify(t, secret); next(); } catch { res.status(401).json({ error: 'Authentication required' }); } };
const roles = (...allowed: string[]) => (req: AR, res: Response, next: NextFunction) => allowed.includes(req.user.role) ? next() : res.status(403).json({ error: 'Permission denied' });
const token = (u: any) => jwt.sign({ id: String(u._id), role: u.role, name: u.name }, secret, { expiresIn: '7d' });
async function stationFor(req: AR, id: string) { const s: any = await Station.findById(id); if (!s) return null; return req.user.role === 'ADMIN' || String(s.owner) === req.user.id || (req.user.role === 'WORKER' && s.workers.some((w: any) => String(w) === req.user.id)) ? s : null; }
async function alert(s: any, title: string, message: string, type: string) { const n = await Notification.create({ recipient: s.owner, title, message, type }); io.to('user:' + s.owner).emit('notification', n); io.to('user:' + s.owner).emit('dashboard:changed'); }
io.on('connection', socket => socket.on('authenticate', (t: string) => { try { socket.join('user:' + (jwt.verify(t, secret) as any).id); } catch {} }));

app.post('/api/auth/register', async (req, res, next) => { try { const v = z.object({ name:z.string().min(2),email:z.string().email(),password:z.string().min(8),phone:z.string().optional() }).parse(req.body); if (await User.exists({email:v.email.toLowerCase()})) return res.status(409).json({error:'Email is already registered'}); const u = await User.create({...v,email:v.email.toLowerCase(),password:await bcrypt.hash(v.password,12)}); res.status(201).json({token:token(u),user:userJson(u)}); } catch(e) { next(e); } });
app.post('/api/auth/login', async (req,res,next) => { try { const v=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body), u:any=await User.findOne({email:v.email.toLowerCase()}).select('+password'); if(!u || !u.isActive || !(await bcrypt.compare(v.password,u.password))) return res.status(401).json({error:'Invalid email or password'}); res.json({token:token(u),user:userJson(u)}); } catch(e){next(e)} });
app.post('/api/auth/forgot-password', (_req,res) => res.json({message:'If the account exists, reset instructions have been sent.'}));
app.get('/api/users/me',auth,async(req:AR,res) => res.json(userJson(await User.findById(req.user.id))));
app.put('/api/users/me',auth,async(req:AR,res,next) => { try { const v=z.object({name:z.string().min(2).optional(),phone:z.string().max(30).optional(),profileImage:z.string().url().optional()}).parse(req.body); res.json(userJson(await User.findByIdAndUpdate(req.user.id,v,{new:true}))); }catch(e){next(e)} });

app.get('/api/stations',auth,async(req:AR,res) => { const q=req.user.role==='ADMIN'?{}:req.user.role==='OWNER'?{owner:req.user.id}:{workers:req.user.id}; const rows:any[]=await Station.find(q).sort({createdAt:-1}); res.json(rows.map(s=>({id:String(s._id),name:s.stationName,stationName:s.stationName,address:s.address,city:s.city,state:s.state,pincode:s.pincode,contact:s.contactNumber,petrolPrice:s.petrolPrice,dieselPrice:s.dieselPrice,fuelTypes:s.fuelTypes,workerIds:s.workers.map(String),status:s.operatingStatus==='ACTIVE'?'Active':'Inactive',createdAt:s.createdAt}))); });
app.post('/api/stations',auth,roles('OWNER','ADMIN'),async(req:AR,res,next)=>{try{const v=z.object({stationName:z.string().min(2),address:z.string().min(3),city:z.string().min(2),state:z.string().min(2),pincode:z.string().min(3),contactNumber:z.string().min(5),petrolPrice:z.coerce.number().min(0),dieselPrice:z.coerce.number().min(0),fuelTypes:z.array(z.string()).optional()}).parse(req.body),s:any=await Station.create({...v,owner:req.user.id});res.status(201).json({id:String(s._id),...s.toObject()});}catch(e){next(e)}});
app.put('/api/stations/:id',auth,roles('OWNER','ADMIN'),async(req:AR,res,next)=>{try{const s:any=await stationFor(req,req.params.id);if(!s)return res.status(404).json({error:'Station not found'});const v=z.object({stationName:z.string().min(2).optional(),address:z.string().min(3).optional(),petrolPrice:z.coerce.number().min(0).optional(),dieselPrice:z.coerce.number().min(0).optional(),operatingStatus:z.enum(['ACTIVE','INACTIVE']).optional()}).parse(req.body);Object.assign(s,v);await s.save();await alert(s,'Station updated',s.stationName+' settings were updated.','station_updated');res.json(s)}catch(e){next(e)}});

app.get('/api/workers',auth,async(req:AR,res)=>{const sts:any[]=await Station.find(req.user.role==='ADMIN'?{}:{owner:req.user.id}),ids=[...new Set(sts.flatMap(s=>s.workers.map(String)))];res.json((await User.find({_id:{$in:ids}})).map(userJson));});
app.post('/api/workers',auth,roles('OWNER','ADMIN'),async(req:AR,res,next)=>{try{const v=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),phone:z.string().optional(),stationId:z.string()}).parse(req.body),s:any=await stationFor(req,v.stationId);if(!s)return res.status(404).json({error:'Station not found'});if(await User.exists({email:v.email}))return res.status(409).json({error:'Email is already in use'});const u:any=await User.create({...v,password:await bcrypt.hash(v.password,12),role:'WORKER',assignedStations:[s._id]});s.workers.push(u._id);await s.save();await alert(s,'Worker added',u.name+' was assigned to '+s.stationName+'.','worker_added');res.status(201).json(userJson(u));}catch(e){next(e)}});

app.post('/api/reports',auth,async(req:AR,res,next)=>{try{const v=z.object({stationId:z.string(),reportDate:z.coerce.date().optional(),petrolOpening:z.coerce.number().min(0),petrolClosing:z.coerce.number().min(0),dieselOpening:z.coerce.number().min(0),dieselClosing:z.coerce.number().min(0),notes:z.string().max(1000).optional()}).parse(req.body),s:any=await stationFor(req,v.stationId);if(!s)return res.status(403).json({error:'Station access denied'});const pl=v.petrolClosing-v.petrolOpening,dl=v.dieselClosing-v.dieselOpening;if(pl<0||dl<0)return res.status(422).json({error:'Closing readings cannot be lower than opening readings'});const d=v.reportDate||new Date(),start=new Date(d);start.setHours(0,0,0,0);const ex:any[]=await Expense.aggregate([{$match:{station:s._id,expenseDate:{$gte:start,$lt:new Date(start.getTime()+86400000)}}},{$group:{_id:null,total:{$sum:'$amount'}}}]),gross=pl*s.petrolPrice+dl*s.dieselPrice,r:any=await Report.create({station:s._id,worker:req.user.id,reportDate:d,petrol:{opening:v.petrolOpening,closing:v.petrolClosing,litres:pl,price:s.petrolPrice,revenue:pl*s.petrolPrice},diesel:{opening:v.dieselOpening,closing:v.dieselClosing,litres:dl,price:s.dieselPrice,revenue:dl*s.dieselPrice},grossRevenue:gross,expensesTotal:ex[0]?.total||0,netRevenue:gross-(ex[0]?.total||0),notes:v.notes});await alert(s,'New daily report','A report was submitted for '+s.stationName+'.','report_submitted');io.to('user:'+s.owner).emit('report:submitted',r);res.status(201).json(r)}catch(e){next(e)}});
app.get('/api/reports',auth,async(req:AR,res)=>{const ids=(await Station.find(req.user.role==='ADMIN'?{}:req.user.role==='OWNER'?{owner:req.user.id}:{workers:req.user.id})).map(s=>s._id),rows:any[]=await Report.find({station:{$in:ids}}).populate('station worker','stationName name').sort({reportDate:-1});res.json(rows.map(r=>({id:String(r._id),stationId:String(r.station._id||r.station),stationName:r.station.stationName,workerName:r.worker.name,petrolSalesLitres:r.petrol.litres,dieselSalesLitres:r.diesel.litres,petrolSalesValue:r.petrol.revenue,dieselSalesValue:r.diesel.revenue,grossIncome:r.grossRevenue,expenses:r.expensesTotal,status:r.status,createdAt:r.createdAt})));});
app.patch('/api/reports/:id/status',auth,roles('OWNER','ADMIN'),async(req:AR,res,next)=>{try{const v=z.object({status:z.enum(['REVIEWED','APPROVED','REJECTED']),rejectionReason:z.string().min(3).optional()}).parse(req.body);if(v.status==='REJECTED'&&!v.rejectionReason)return res.status(422).json({error:'A rejection reason is required'});const r:any=await Report.findById(req.params.id);if(!r||!(await stationFor(req,String(r.station))))return res.status(404).json({error:'Report not found'});Object.assign(r,v);await r.save();res.json(r)}catch(e){next(e)}});

app.post('/api/payments',auth,async(req:AR,res,next)=>{try{const v=z.object({stationId:z.string(),reportId:z.string().optional(),amount:z.coerce.number().positive(),paymentMethod:z.enum(['CASH','UPI','CARD','CREDIT','OTHER']),transactionReference:z.string().max(100).optional(),description:z.string().max(500).optional(),transactionDate:z.coerce.date().optional()}).parse(req.body),s:any=await stationFor(req,v.stationId);if(!s)return res.status(403).json({error:'Station access denied'});const p:any=await Payment.create({...v,station:s._id,report:v.reportId,worker:req.user.id,transactionDate:v.transactionDate||new Date()});await alert(s,'Payment recorded','₹'+p.amount+' received via '+p.paymentMethod+'.','transaction');io.to('user:'+s.owner).emit('payment:recorded',p);res.status(201).json(p)}catch(e){next(e)}});
app.get('/api/payments',auth,async(req:AR,res)=>{const ids=(await Station.find(req.user.role==='ADMIN'?{}:req.user.role==='OWNER'?{owner:req.user.id}:{workers:req.user.id})).map(s=>s._id);res.json(await Payment.find({station:{$in:ids}}).sort({transactionDate:-1}));});
app.post('/api/expenses',auth,async(req:AR,res,next)=>{try{const v=z.object({stationId:z.string(),category:z.enum(['Electricity','Maintenance','Staff','Transportation','Supplies','Equipment','Other']),amount:z.coerce.number().positive(),description:z.string().max(500).optional(),expenseDate:z.coerce.date().optional()}).parse(req.body),s:any=await stationFor(req,v.stationId);if(!s)return res.status(403).json({error:'Station access denied'});const x:any=await Expense.create({...v,station:s._id,uploadedBy:req.user.id,expenseDate:v.expenseDate||new Date()});await alert(s,'Expense submitted','₹'+x.amount+' '+x.category+' expense needs review.','expense_submitted');res.status(201).json(x)}catch(e){next(e)}});
app.get('/api/expenses',auth,async(req:AR,res)=>{const ids=(await Station.find(req.user.role==='ADMIN'?{}:req.user.role==='OWNER'?{owner:req.user.id}:{workers:req.user.id})).map(s=>s._id);res.json(await Expense.find({station:{$in:ids}}).sort({expenseDate:-1}));});

app.get('/api/analytics/dashboard',auth,async(req:AR,res)=>{const ids=(await Station.find(req.user.role==='ADMIN'?{}:req.user.role==='OWNER'?{owner:req.user.id}:{workers:req.user.id})).map(s=>s._id),d=new Date();d.setHours(0,0,0,0);const [r,x,p,w]=await Promise.all([Report.find({station:{$in:ids},reportDate:{$gte:d}}),Expense.find({station:{$in:ids},expenseDate:{$gte:d}}),Payment.find({station:{$in:ids},transactionDate:{$gte:d}}),User.countDocuments({assignedStations:{$in:ids},role:'WORKER',isActive:true})]);const sum=(a:any[],k:string)=>a.reduce((n,v)=>n+(v[k]||0),0),gross=sum(r,'grossRevenue'),expenses=sum(x,'amount');res.json({todayGrossRevenue:gross,todayExpenses:expenses,todayNetRevenue:gross-expenses,todayFuelSales:r.reduce((n:any,v:any)=>n+v.petrol.litres+v.diesel.litres,0),activeWorkers:w,totalStations:ids.length,totalPayments:sum(p,'amount'),paymentMethods:['CASH','UPI','CARD','CREDIT','OTHER'].map(method=>({method,value:p.filter((v:any)=>v.paymentMethod===method).reduce((n:any,v:any)=>n+v.amount,0)}))});});
app.get('/api/analytics/:metric',auth,async(req:AR,res)=>{const ids=(await Station.find(req.user.role==='ADMIN'?{}:req.user.role==='OWNER'?{owner:req.user.id}:{workers:req.user.id})).map(s=>s._id),from=req.query.from?new Date(String(req.query.from)):new Date(Date.now()-30*86400000),to=req.query.to?new Date(String(req.query.to)):new Date();const rows=await Report.aggregate([{$match:{station:{$in:ids},reportDate:{$gte:from,$lte:to}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$reportDate'}},grossRevenue:{$sum:'$grossRevenue'},netRevenue:{$sum:'$netRevenue'},petrolLitres:{$sum:'$petrol.litres'},dieselLitres:{$sum:'$diesel.litres'}}},{$sort:{_id:1}}]);res.json(rows.map(r=>({date:r._id,...r})));});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
app.post('/api/bills',auth,upload.single('file'),async(req:AR,res,next)=>{try{const file=(req as any).file;if(!file||!process.env.CLOUDINARY_CLOUD_NAME)return res.status(422).json({error:'A file and configured Cloudinary storage are required'});const s=await stationFor(req,String(req.body.stationId));if(!s)return res.status(403).json({error:'Station access denied'});const v:any=await new Promise((ok,no)=>cloudinary.uploader.upload_stream({resource_type:'auto',folder:'fuelflow/bills'},(e,x)=>e?no(e):ok(x)).end(file.buffer));res.status(201).json({url:v.secure_url,publicId:v.public_id,name:file.originalname});}catch(e){next(e)}});
app.get('/api/notifications',auth,async(req:AR,res)=>res.json(await Notification.find({recipient:req.user.id}).sort({createdAt:-1}).limit(100)));
app.post('/api/notifications/:id/read',auth,async(req:AR,res)=>{const n=await Notification.findOneAndUpdate({_id:req.params.id,recipient:req.user.id},{isRead:true},{new:true});n?res.json(n):res.status(404).json({error:'Notification not found'});});
app.use((e:any,_q:Request,res:Response,_n:NextFunction)=>{if(e instanceof z.ZodError)return res.status(422).json({error:'Validation failed',details:e.issues});if(e?.code===11000)return res.status(409).json({error:'A record with that value already exists'});console.error(e);res.status(500).json({error:'Unexpected server error'});});
async function start() {
  let mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/fuelflow';

  if (!process.env.MONGODB_URI && process.env.NODE_ENV !== 'production') {
    const memoryMongo = await MongoMemoryServer.create({
      instance: { dbName: 'fuelflow' },
      binary: { version: '7.0.14' }
    });
    mongoUri = memoryMongo.getUri();
    console.log('Using in-memory MongoDB for local development at', mongoUri);
  }

  await mongoose.connect(mongoUri);

  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({ server: { middlewareMode: true }, appType: 'spa' });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(process.cwd(), 'dist')));
  }

  server.listen(PORT, () => console.log('FuelFlow listening on ' + PORT));
}

start().catch(e => {
  console.error('Unable to start FuelFlow:', e.message);
  process.exit(1);
});
